name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize]

jobs:
  yarn-operation:
    uses: anjar-org/core-pipeline/.github/workflows/yarn-operation.yml@main
    secrets: inherit
  build-deploy:
    uses: anjar-org/core-pipeline/.github/workflows/main-workflow.yml@main
    secrets: inherit


