name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize]

jobs:
  deploy:
    uses: anjar-org/core-pipeline/.github/workflows/main-workflow.yml@main
    with:
      config-path: .github/labeler.yml
    secrets: inheri


